version: '3.8'

services:  
  tfuchs-portfolio:
    container_name: portfolio-v3
    build:
      dockerfile: Dockerfile
      context: ./
      target: ${TARGET}
    environment:
      VIRTUAL_HOST: ${VHOST}
      LETSENCRYPT_HOST: ${VHOST}
      VIRTUAL_PORT: 3000
    restart: on-failure
    volumes:
      - ./:/app
      - portfolio-front-next:/app/.next
      - portfolio-front-modules:/app/node_modules
    ports:
      - ${PORT_FRONT}:3000
    networks:
      - net


volumes:
  portfolio-front-next:
  portfolio-front-modules:
    
networks:
  net:
    external: true
